extends: 
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime

env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

settings:
  "import/resolver":
    node:
      "moduleDirectory":
        - "node_modules"
        - "src"

rules:
  "object-curly-newline": 
    - "error"
    - "consistent": true

  "react/prop-types": "off"
  "react/jsx-props-no-spreading": "off"
  
  "no-confusing-arrow": "off"
  "implicit-arrow-linebreak": "off"

