extends: 
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime

env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

settings:
  "import/resolver":
    node:
      "moduleDirectory":
        - "node_modules"
        - "src"

rules:
  "react/prop-types": "off"