extends: airbnb

env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: {
  'indent': ['error', 2],
  'quotes': ['error', 'single'],
  'no-multi-spaces': ['error'],
  'semi': ['error', 'always'],
  'react/prop-types': 'off'
}
