env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'quotes': ['error', 'single'],
  'semi': ['error', 'always'],
  'indent': ['error', 2],
  'no-multi-spaces': ['error']
}
