version: '3'
silent: true

tasks:
  fmt:
    dir: terraform
    cmd: terraform fmt -recursive

  init:
    dir: terraform
    cmd: terraform init

  plan:
    dir: terraform
    cmd: terraform plan

  apply:
    dir: terraform
    cmd: terraform apply

  build:
    cmd: node esbuild.js

  start:
    cmd: node esbuild.js --serve

  invalidate:
    cmds: 
      - |
        aws cloudfront create-invalidation \
          --distribution-id E2NWH87KQ3CPU8 \
          --no-cli-pager \
          --paths '/*' 

  deploy:
    cmds:
      - task: build
      - task: apply
      - task: invalidate

  

